channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=23.0.1
- pip:
  - mlflow<3,>=2.2
  - cffi==1.15.1
  - click==8.0.4
  - cloudpickle==2.0.0
  - cython==0.29.33
  - cytoolz==0.12.0
  - defusedxml==0.7.1
  - distributed==2022.2.1
  - graphviz==0.20.1
  - jinja2==3.1.2
  - lightgbm==3.3.5
  - matplotlib==3.6.3
  - numpy==1.21.5
  - packaging==21.3
  - pandas==1.5.3
  - pathlib==1.0.1
  - python-snappy==0.6.1
  - pyyaml==6.0
  - scikit-learn==1.2.1
  - scipy==1.10.0
  - typing-extensions==4.4.0
  - zstandard==0.19.0
name: mlflow-env
